# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensoris/protobuf/types/map.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from sensoris.protobuf.types import base_pb2 as sensoris_dot_protobuf_dot_types_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!sensoris/protobuf/types/map.proto\x12\x1bsensoris.protobuf.types.map\x1a\x1egoogle/protobuf/wrappers.proto\x1a\"sensoris/protobuf/types/base.proto\"A\n\x0fMapTilingScheme\x12.\n\x03urn\x18\x01 \x01(\x0b\x32!.sensoris.protobuf.types.base.Urn\"\x7f\n\x08MapTiles\x12\x43\n\rtiling_scheme\x18\x01 \x01(\x0b\x32,.sensoris.protobuf.types.map.MapTilingScheme\x12.\n\x08tile_ids\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\">\n\x0cMapAttribute\x12.\n\x03urn\x18\x01 \x01(\x0b\x32!.sensoris.protobuf.types.base.Urn\"\x82\x01\n\x14MapAttributeAndValue\x12<\n\tattribute\x18\x01 \x01(\x0b\x32).sensoris.protobuf.types.map.MapAttribute\x12,\n\x06values\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueBY\n\x16org.sensoris.types.mapB\x10SensorisMapTypesP\x01Z(sensoris.org/specification/types/mapping\xf8\x01\x01\x62\x06proto3')



_MAPTILINGSCHEME = DESCRIPTOR.message_types_by_name['MapTilingScheme']
_MAPTILES = DESCRIPTOR.message_types_by_name['MapTiles']
_MAPATTRIBUTE = DESCRIPTOR.message_types_by_name['MapAttribute']
_MAPATTRIBUTEANDVALUE = DESCRIPTOR.message_types_by_name['MapAttributeAndValue']
MapTilingScheme = _reflection.GeneratedProtocolMessageType('MapTilingScheme', (_message.Message,), {
  'DESCRIPTOR' : _MAPTILINGSCHEME,
  '__module__' : 'sensoris.protobuf.types.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.types.map.MapTilingScheme)
  })
_sym_db.RegisterMessage(MapTilingScheme)

MapTiles = _reflection.GeneratedProtocolMessageType('MapTiles', (_message.Message,), {
  'DESCRIPTOR' : _MAPTILES,
  '__module__' : 'sensoris.protobuf.types.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.types.map.MapTiles)
  })
_sym_db.RegisterMessage(MapTiles)

MapAttribute = _reflection.GeneratedProtocolMessageType('MapAttribute', (_message.Message,), {
  'DESCRIPTOR' : _MAPATTRIBUTE,
  '__module__' : 'sensoris.protobuf.types.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.types.map.MapAttribute)
  })
_sym_db.RegisterMessage(MapAttribute)

MapAttributeAndValue = _reflection.GeneratedProtocolMessageType('MapAttributeAndValue', (_message.Message,), {
  'DESCRIPTOR' : _MAPATTRIBUTEANDVALUE,
  '__module__' : 'sensoris.protobuf.types.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.types.map.MapAttributeAndValue)
  })
_sym_db.RegisterMessage(MapAttributeAndValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.sensoris.types.mapB\020SensorisMapTypesP\001Z(sensoris.org/specification/types/mapping\370\001\001'
  _MAPTILINGSCHEME._serialized_start=134
  _MAPTILINGSCHEME._serialized_end=199
  _MAPTILES._serialized_start=201
  _MAPTILES._serialized_end=328
  _MAPATTRIBUTE._serialized_start=330
  _MAPATTRIBUTE._serialized_end=392
  _MAPATTRIBUTEANDVALUE._serialized_start=395
  _MAPATTRIBUTEANDVALUE._serialized_end=525
# @@protoc_insertion_point(module_scope)
