# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensoris/protobuf/categories/driving_behavior.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensoris.protobuf.types import base_pb2 as sensoris_dot_protobuf_dot_types_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3sensoris/protobuf/categories/driving_behavior.proto\x12,sensoris.protobuf.categories.drivingbehavior\x1a\"sensoris/protobuf/types/base.proto\"\x84\x07\n\rParkingStatus\x12=\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32+.sensoris.protobuf.types.base.EventEnvelope\x12n\n\x15status_and_confidence\x18\x02 \x01(\x0b\x32O.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence\x12t\n\x18\x64irection_and_confidence\x18\x03 \x01(\x0b\x32R.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence\x12X\n\x15\x64uration_and_accuracy\x18\x04 \x01(\x0b\x32\x33.sensoris.protobuf.types.base.Int64ValueAndAccuracyB\x04\x88\xb5\x18\x00\x1a\xec\x01\n\x13StatusAndConfidence\x12\x62\n\x04type\x18\x01 \x01(\x0e\x32T.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence.Type\x12<\n\nconfidence\x18\x02 \x01(\x0b\x32(.sensoris.protobuf.types.base.Confidence\"3\n\x04Type\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x0b\n\x07PARK_IN\x10\x01\x12\x0c\n\x08PARK_OUT\x10\x02\x1a\x84\x02\n\x16\x44irectionAndConfidence\x12\x65\n\x04type\x18\x01 \x01(\x0e\x32W.sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence.Type\x12<\n\nconfidence\x18\x02 \x01(\x0b\x32(.sensoris.protobuf.types.base.Confidence\"E\n\x04Type\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x10\n\x0cLONGITUDINAL\x10\x01\x12\x0b\n\x07LATERAL\x10\x02\x12\x0c\n\x08\x44IAGONAL\x10\x03\"\xb0\x01\n\x17\x44rivingBehaviorCategory\x12@\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32..sensoris.protobuf.types.base.CategoryEnvelope\x12S\n\x0eparking_status\x18\x02 \x03(\x0b\x32;.sensoris.protobuf.categories.drivingbehavior.ParkingStatusB\x86\x01\n\'org.sensoris.categories.drivingbehaviorB\x1fSensorisDrivingBehaviorCategoryP\x01Z5sensoris.org/specification/categories/drivingbehavior\xf8\x01\x01\x62\x06proto3')



_PARKINGSTATUS = DESCRIPTOR.message_types_by_name['ParkingStatus']
_PARKINGSTATUS_STATUSANDCONFIDENCE = _PARKINGSTATUS.nested_types_by_name['StatusAndConfidence']
_PARKINGSTATUS_DIRECTIONANDCONFIDENCE = _PARKINGSTATUS.nested_types_by_name['DirectionAndConfidence']
_DRIVINGBEHAVIORCATEGORY = DESCRIPTOR.message_types_by_name['DrivingBehaviorCategory']
_PARKINGSTATUS_STATUSANDCONFIDENCE_TYPE = _PARKINGSTATUS_STATUSANDCONFIDENCE.enum_types_by_name['Type']
_PARKINGSTATUS_DIRECTIONANDCONFIDENCE_TYPE = _PARKINGSTATUS_DIRECTIONANDCONFIDENCE.enum_types_by_name['Type']
ParkingStatus = _reflection.GeneratedProtocolMessageType('ParkingStatus', (_message.Message,), {

  'StatusAndConfidence' : _reflection.GeneratedProtocolMessageType('StatusAndConfidence', (_message.Message,), {
    'DESCRIPTOR' : _PARKINGSTATUS_STATUSANDCONFIDENCE,
    '__module__' : 'sensoris.protobuf.categories.driving_behavior_pb2'
    # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.drivingbehavior.ParkingStatus.StatusAndConfidence)
    })
  ,

  'DirectionAndConfidence' : _reflection.GeneratedProtocolMessageType('DirectionAndConfidence', (_message.Message,), {
    'DESCRIPTOR' : _PARKINGSTATUS_DIRECTIONANDCONFIDENCE,
    '__module__' : 'sensoris.protobuf.categories.driving_behavior_pb2'
    # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.drivingbehavior.ParkingStatus.DirectionAndConfidence)
    })
  ,
  'DESCRIPTOR' : _PARKINGSTATUS,
  '__module__' : 'sensoris.protobuf.categories.driving_behavior_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.drivingbehavior.ParkingStatus)
  })
_sym_db.RegisterMessage(ParkingStatus)
_sym_db.RegisterMessage(ParkingStatus.StatusAndConfidence)
_sym_db.RegisterMessage(ParkingStatus.DirectionAndConfidence)

DrivingBehaviorCategory = _reflection.GeneratedProtocolMessageType('DrivingBehaviorCategory', (_message.Message,), {
  'DESCRIPTOR' : _DRIVINGBEHAVIORCATEGORY,
  '__module__' : 'sensoris.protobuf.categories.driving_behavior_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.drivingbehavior.DrivingBehaviorCategory)
  })
_sym_db.RegisterMessage(DrivingBehaviorCategory)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'org.sensoris.categories.drivingbehaviorB\037SensorisDrivingBehaviorCategoryP\001Z5sensoris.org/specification/categories/drivingbehavior\370\001\001'
  _PARKINGSTATUS.fields_by_name['duration_and_accuracy']._options = None
  _PARKINGSTATUS.fields_by_name['duration_and_accuracy']._serialized_options = b'\210\265\030\000'
  _PARKINGSTATUS._serialized_start=138
  _PARKINGSTATUS._serialized_end=1038
  _PARKINGSTATUS_STATUSANDCONFIDENCE._serialized_start=539
  _PARKINGSTATUS_STATUSANDCONFIDENCE._serialized_end=775
  _PARKINGSTATUS_STATUSANDCONFIDENCE_TYPE._serialized_start=724
  _PARKINGSTATUS_STATUSANDCONFIDENCE_TYPE._serialized_end=775
  _PARKINGSTATUS_DIRECTIONANDCONFIDENCE._serialized_start=778
  _PARKINGSTATUS_DIRECTIONANDCONFIDENCE._serialized_end=1038
  _PARKINGSTATUS_DIRECTIONANDCONFIDENCE_TYPE._serialized_start=969
  _PARKINGSTATUS_DIRECTIONANDCONFIDENCE_TYPE._serialized_end=1038
  _DRIVINGBEHAVIORCATEGORY._serialized_start=1041
  _DRIVINGBEHAVIORCATEGORY._serialized_end=1217
# @@protoc_insertion_point(module_scope)
