# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensoris/protobuf/categories/etsi_denm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sensoris/protobuf/categories/etsi_denm.proto\x12%sensoris.protobuf.categories.etsidenm\x1a\x1egoogle/protobuf/wrappers.proto\"\x7f\n\x10\x45tsiDenmCategory\x12*\n\x05width\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12+\n\x06height\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x42q\n org.sensoris.categories.etsidenmB\x18SensorisEtsiDenmCategoryP\x01Z.sensoris.org/specification/categories/etsidenm\xf8\x01\x01\x62\x06proto3')



_ETSIDENMCATEGORY = DESCRIPTOR.message_types_by_name['EtsiDenmCategory']
EtsiDenmCategory = _reflection.GeneratedProtocolMessageType('EtsiDenmCategory', (_message.Message,), {
  'DESCRIPTOR' : _ETSIDENMCATEGORY,
  '__module__' : 'sensoris.protobuf.categories.etsi_denm_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.etsidenm.EtsiDenmCategory)
  })
_sym_db.RegisterMessage(EtsiDenmCategory)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n org.sensoris.categories.etsidenmB\030SensorisEtsiDenmCategoryP\001Z.sensoris.org/specification/categories/etsidenm\370\001\001'
  _ETSIDENMCATEGORY._serialized_start=119
  _ETSIDENMCATEGORY._serialized_end=246
# @@protoc_insertion_point(module_scope)
