# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensoris/protobuf/categories/map.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensoris.protobuf.types import base_pb2 as sensoris_dot_protobuf_dot_types_dot_base__pb2
from sensoris.protobuf.types import spatial_pb2 as sensoris_dot_protobuf_dot_types_dot_spatial__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&sensoris/protobuf/categories/map.proto\x12 sensoris.protobuf.categories.map\x1a\"sensoris/protobuf/types/base.proto\x1a%sensoris/protobuf/types/spatial.proto\"\xa0\x01\n\x0cMapReference\x12=\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32+.sensoris.protobuf.types.base.EventEnvelope\x12Q\n\x12location_reference\x18\x02 \x01(\x0b\x32\x35.sensoris.protobuf.types.spatial.MapLocationReference\"\x96\x01\n\x0bMapCategory\x12@\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32..sensoris.protobuf.types.base.CategoryEnvelope\x12\x45\n\rmap_reference\x18\x02 \x03(\x0b\x32..sensoris.protobuf.categories.map.MapReferenceBf\n\x1borg.sensoris.categories.mapB\x13SensorisMapCategoryP\x01Z-sensoris.org/specification/categories/mapping\xf8\x01\x01\x62\x06proto3')



_MAPREFERENCE = DESCRIPTOR.message_types_by_name['MapReference']
_MAPCATEGORY = DESCRIPTOR.message_types_by_name['MapCategory']
MapReference = _reflection.GeneratedProtocolMessageType('MapReference', (_message.Message,), {
  'DESCRIPTOR' : _MAPREFERENCE,
  '__module__' : 'sensoris.protobuf.categories.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.map.MapReference)
  })
_sym_db.RegisterMessage(MapReference)

MapCategory = _reflection.GeneratedProtocolMessageType('MapCategory', (_message.Message,), {
  'DESCRIPTOR' : _MAPCATEGORY,
  '__module__' : 'sensoris.protobuf.categories.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.map.MapCategory)
  })
_sym_db.RegisterMessage(MapCategory)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033org.sensoris.categories.mapB\023SensorisMapCategoryP\001Z-sensoris.org/specification/categories/mapping\370\001\001'
  _MAPREFERENCE._serialized_start=152
  _MAPREFERENCE._serialized_end=312
  _MAPCATEGORY._serialized_start=315
  _MAPCATEGORY._serialized_end=465
# @@protoc_insertion_point(module_scope)
